Repository VulnerabilityHistoryProject/httpd-vulnerabilities, pull requests merged in 2019-04, with the labels that each got.

#50 Complete CVE-2008-0456
  cves/CVE-2008-0456.yml
  cves/CVE-2016-1546.yml
Labels: Cohort Q

#49 CVE-2007-6422
  cves/CVE-2007-6422.yml
Labels: Cohort P

#48 update CVE-2006-5752
  cves/CVE-2006-5752.yml
Labels: Cohort M

#47 CVE-2004-0113
  cves/CVE-2004-0113.yml
Labels: Cohort F

#23 CVE-2005-2728
  cves/CVE-2005-2728.yml
Labels: Cohort L

#20 CVE-2005-2700
  cves/CVE-2005-2700.yml
Labels: Cohort K

#46 khk8083 pull request for CVE-2006-3747
  cves/CVE-2006-3747.yml
Labels: Cohort M

#45 CVE-2003-0020
  cves/CVE-2003-0020.yml
Labels: Cohort C

#43 CVE-2007-1862
  cves/CVE-2007-1862.yml
Labels: Cohort O

#42 CVE-2004-0942
  cves/CVE-2004-0942.yml
Labels: Cohort J

#41 CVE-2016-8743 and CVE-2008-0005
  cves/CVE-2008-0005.yml
  cves/CVE-2016-8743.yml
Labels: Cohort Q

#40 CVE-2004-0174
  cves/CVE-2004-0174.yml
Labels: Cohort F

#39 CVE-2003-0083: Filtered escape sequences
  cves/CVE-2003-0083.yml
Labels: Cohort C

#38 CVE-2008-2939
  .gitignore
  README.md
  cves/CVE-2008-2939.yml
  cves/CVE-2010-1623.yml
  scripts/cve-parsing/finalPublishedDates
  scripts/cve-parsing/write-dates2-cves.py
Labels: Cohort Q

#37 CVE-2016-2161 CVE-2008-2364
  cves/CVE-2008-2364.yml
  cves/CVE-2016-2161.yml
Labels: Cohort Q

#36 CVE-2002-1593
  cves/CVE-2002-1593.yml
Labels: Cohort C

#35 CVE-2005-1268
  cves/CVE-2005-1268.yml
Labels: Cohort K

#34 CVE-2007-3847
  cves/CVE-2007-3847.yml
Labels: Cohort O

#33 CVE-2017-7659
  cves/CVE-2017-7659.yml
Labels: Cohort O

#32 CVE-2005-2088
  cves/CVE-2005-2088.yml
Labels: Cohort K

#30 CVE-2005-3357
  cves/CVE-2005-3357.yml
Labels: Cohort M

#29 CVE-2004-0751
  cves/CVE-2004-0751.yml
Labels: Cohort I

#26 CVE-2002-0661 path traversal using backslash
  cves/CVE-2002-0661.yml
Labels: Cohort A

#25 CVE-2009-1191 and CVE-2016-5387
  cves/CVE-2009-1191.yml
  cves/CVE-2016-5387.yml
Labels: Cohort G

#24 CVE-2017-7679
  cves/CVE-2017-7679.yml
Labels: Cohort O
