Repository VulnerabilityHistoryProject/httpd-vulnerabilities, pull requests merged in 2020-02, with the labels that each got.

#94 CVE-2013-2249
  Gemfile.lock
  cves/CVE-2013-2249.yml
Labels: Cohort I

#93 CVE-2013-1896
  cves/CVE-2013-1896.yml
Labels: Cohort E

#91 CVE-2011-0117
  cves/CVE-2014-0117.yml
Labels: Cohort O

#87 CVE-2002-0840
  cves/CVE-2002-0840.yml
Labels: Cohort M

#86 CVE-2014-0231
  cves/CVE-2014-0231.yml
Labels: Cohort J

#85 CVE-2005-2970
  cves/CVE-2005-2970.yml
Labels: Cohort K

#84 CVE-2004-0809
  cves/CVE-2004-0809.yml
Labels: Cohort P

#83 CVE-2011-3192
  cves/CVE-2011-3192.yml
Labels: Cohort F

#81 CVE-2004-1834
  cves/CVE-2004-1834.yml
Labels: Cohort C

#80 CVE-2015-3183
  cves/CVE-2015-3183.yml
Labels: Cohort B

#79 CVE-2009-1195
  cves/CVE-2009-1195.yml
Labels: Cohort T

#78 CVE-2017-9798
  cves/CVE-2017-9798.yml
Labels: Cohort I

#77 CVE-2004-0811
  cves/CVE-2004-0811.yml
Labels: Cohort G

#76 CVE-2010-1452
  cves/CVE-2010-1452.yml
Labels: Cohort C

#75 CVE-2007-6388
  cves/CVE-2007-6388.yml
Labels: Cohort H

#73 CVE-2014-8109
  cves/CVE-2014-8109.yml
Labels: Cohort B

#72 CVE-2009-3095
  cves/CVE-2009-3095.yml
Labels: Cohort T

#71 CVE-2012-0031
  cves/CVE-2012-0031.yml
Labels: Cohort D

#70 CVE-2010-2068
  cves/CVE-2010-2068.yml
Labels: Cohort D

#69 CVE-2016-8740
  cves/CVE-2016-8740.yml
Labels: Cohort L

#68 CVE-2010-0425
  cves/CVE-2010-0425.yml
Labels: Cohort N

#67 CVE-2003-0253
  cves/CVE-2003-0253.yml
Labels: Cohort I

#66 CVE 2014-3583
  cves/CVE-2014-3583.yml
Labels: Cohort E

#65 CVE-2014-3581
  cves/CVE-2014-3581.yml
Labels: Cohort A

#64 CVE-2014-3523
  cves/CVE-2014-3523.yml
Labels: Cohort R

#62 Added CVE-2004-0747 Information
  cves/CVE-2004-0747.yml
Labels: Cohort S
